/*
 * LXD
 * The services listed below are referred as .....
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@relxd.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.relxd.lxd.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * FileSystemMountOptionsAndThinPoolConfig
 */
@JsonPropertyOrder({
  FileSystemMountOptionsAndThinPoolConfig.JSON_PROPERTY_SIZE,
  FileSystemMountOptionsAndThinPoolConfig.JSON_PROPERTY_SOURCE,
  FileSystemMountOptionsAndThinPoolConfig.JSON_PROPERTY_USED_BY,
  FileSystemMountOptionsAndThinPoolConfig.JSON_PROPERTY_VOLUME_BLOCK_FILESYSTEM,
  FileSystemMountOptionsAndThinPoolConfig.JSON_PROPERTY_VOLUME_BLOCK_MOUNT_OPTIONS,
  FileSystemMountOptionsAndThinPoolConfig.JSON_PROPERTY_LVM_THINPOOL_NAME,
  FileSystemMountOptionsAndThinPoolConfig.JSON_PROPERTY_LVM_VG_NAME,
  FileSystemMountOptionsAndThinPoolConfig.JSON_PROPERTY_VOLUME_SIZE
})
@javax.annotation.processing.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class FileSystemMountOptionsAndThinPoolConfig {
  public static final String JSON_PROPERTY_SIZE = "size";
  private String size;

  public static final String JSON_PROPERTY_SOURCE = "source";
  private String source;

  public static final String JSON_PROPERTY_USED_BY = "used_by";
  private String usedBy;

  public static final String JSON_PROPERTY_VOLUME_BLOCK_FILESYSTEM = "volume.block.filesystem";
  private String volumeBlockFilesystem;

  public static final String JSON_PROPERTY_VOLUME_BLOCK_MOUNT_OPTIONS = "volume.block.mount_options";
  private String volumeBlockMountOptions;

  public static final String JSON_PROPERTY_LVM_THINPOOL_NAME = "lvm.thinpool_name";
  private String lvmThinpoolName;

  public static final String JSON_PROPERTY_LVM_VG_NAME = "lvm.vg_name";
  private String lvmVgName;

  public static final String JSON_PROPERTY_VOLUME_SIZE = "volume.size";
  private String volumeSize;


  public FileSystemMountOptionsAndThinPoolConfig size(String size) {
    this.size = size;
    return this;
  }

   /**
   * Get size
   * @return size
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "15032385536", value = "")
  @JsonProperty(JSON_PROPERTY_SIZE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSize() {
    return size;
  }


  @JsonProperty(JSON_PROPERTY_SIZE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSize(String size) {
    this.size = size;
  }


  public FileSystemMountOptionsAndThinPoolConfig source(String source) {
    this.source = source;
    return this;
  }

   /**
   * Get source
   * @return source
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "pool1", value = "")
  @JsonProperty(JSON_PROPERTY_SOURCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSource() {
    return source;
  }


  @JsonProperty(JSON_PROPERTY_SOURCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSource(String source) {
    this.source = source;
  }


  public FileSystemMountOptionsAndThinPoolConfig usedBy(String usedBy) {
    this.usedBy = usedBy;
    return this;
  }

   /**
   * Get usedBy
   * @return usedBy
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_USED_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUsedBy() {
    return usedBy;
  }


  @JsonProperty(JSON_PROPERTY_USED_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUsedBy(String usedBy) {
    this.usedBy = usedBy;
  }


  public FileSystemMountOptionsAndThinPoolConfig volumeBlockFilesystem(String volumeBlockFilesystem) {
    this.volumeBlockFilesystem = volumeBlockFilesystem;
    return this;
  }

   /**
   * Get volumeBlockFilesystem
   * @return volumeBlockFilesystem
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "xfs", value = "")
  @JsonProperty(JSON_PROPERTY_VOLUME_BLOCK_FILESYSTEM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getVolumeBlockFilesystem() {
    return volumeBlockFilesystem;
  }


  @JsonProperty(JSON_PROPERTY_VOLUME_BLOCK_FILESYSTEM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVolumeBlockFilesystem(String volumeBlockFilesystem) {
    this.volumeBlockFilesystem = volumeBlockFilesystem;
  }


  public FileSystemMountOptionsAndThinPoolConfig volumeBlockMountOptions(String volumeBlockMountOptions) {
    this.volumeBlockMountOptions = volumeBlockMountOptions;
    return this;
  }

   /**
   * Get volumeBlockMountOptions
   * @return volumeBlockMountOptions
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "discard", value = "")
  @JsonProperty(JSON_PROPERTY_VOLUME_BLOCK_MOUNT_OPTIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getVolumeBlockMountOptions() {
    return volumeBlockMountOptions;
  }


  @JsonProperty(JSON_PROPERTY_VOLUME_BLOCK_MOUNT_OPTIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVolumeBlockMountOptions(String volumeBlockMountOptions) {
    this.volumeBlockMountOptions = volumeBlockMountOptions;
  }


  public FileSystemMountOptionsAndThinPoolConfig lvmThinpoolName(String lvmThinpoolName) {
    this.lvmThinpoolName = lvmThinpoolName;
    return this;
  }

   /**
   * Get lvmThinpoolName
   * @return lvmThinpoolName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "LXDThinPool", value = "")
  @JsonProperty(JSON_PROPERTY_LVM_THINPOOL_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLvmThinpoolName() {
    return lvmThinpoolName;
  }


  @JsonProperty(JSON_PROPERTY_LVM_THINPOOL_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLvmThinpoolName(String lvmThinpoolName) {
    this.lvmThinpoolName = lvmThinpoolName;
  }


  public FileSystemMountOptionsAndThinPoolConfig lvmVgName(String lvmVgName) {
    this.lvmVgName = lvmVgName;
    return this;
  }

   /**
   * Get lvmVgName
   * @return lvmVgName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "pool1", value = "")
  @JsonProperty(JSON_PROPERTY_LVM_VG_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLvmVgName() {
    return lvmVgName;
  }


  @JsonProperty(JSON_PROPERTY_LVM_VG_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLvmVgName(String lvmVgName) {
    this.lvmVgName = lvmVgName;
  }


  public FileSystemMountOptionsAndThinPoolConfig volumeSize(String volumeSize) {
    this.volumeSize = volumeSize;
    return this;
  }

   /**
   * Get volumeSize
   * @return volumeSize
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "10737418240", value = "")
  @JsonProperty(JSON_PROPERTY_VOLUME_SIZE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getVolumeSize() {
    return volumeSize;
  }


  @JsonProperty(JSON_PROPERTY_VOLUME_SIZE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVolumeSize(String volumeSize) {
    this.volumeSize = volumeSize;
  }


  /**
   * Return true if this FileSystemMountOptionsAndThinPoolConfig object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FileSystemMountOptionsAndThinPoolConfig fileSystemMountOptionsAndThinPoolConfig = (FileSystemMountOptionsAndThinPoolConfig) o;
    return Objects.equals(this.size, fileSystemMountOptionsAndThinPoolConfig.size) &&
        Objects.equals(this.source, fileSystemMountOptionsAndThinPoolConfig.source) &&
        Objects.equals(this.usedBy, fileSystemMountOptionsAndThinPoolConfig.usedBy) &&
        Objects.equals(this.volumeBlockFilesystem, fileSystemMountOptionsAndThinPoolConfig.volumeBlockFilesystem) &&
        Objects.equals(this.volumeBlockMountOptions, fileSystemMountOptionsAndThinPoolConfig.volumeBlockMountOptions) &&
        Objects.equals(this.lvmThinpoolName, fileSystemMountOptionsAndThinPoolConfig.lvmThinpoolName) &&
        Objects.equals(this.lvmVgName, fileSystemMountOptionsAndThinPoolConfig.lvmVgName) &&
        Objects.equals(this.volumeSize, fileSystemMountOptionsAndThinPoolConfig.volumeSize);
  }

  @Override
  public int hashCode() {
    return Objects.hash(size, source, usedBy, volumeBlockFilesystem, volumeBlockMountOptions, lvmThinpoolName, lvmVgName, volumeSize);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FileSystemMountOptionsAndThinPoolConfig {\n");
    sb.append("    size: ").append(toIndentedString(size)).append("\n");
    sb.append("    source: ").append(toIndentedString(source)).append("\n");
    sb.append("    usedBy: ").append(toIndentedString(usedBy)).append("\n");
    sb.append("    volumeBlockFilesystem: ").append(toIndentedString(volumeBlockFilesystem)).append("\n");
    sb.append("    volumeBlockMountOptions: ").append(toIndentedString(volumeBlockMountOptions)).append("\n");
    sb.append("    lvmThinpoolName: ").append(toIndentedString(lvmThinpoolName)).append("\n");
    sb.append("    lvmVgName: ").append(toIndentedString(lvmVgName)).append("\n");
    sb.append("    volumeSize: ").append(toIndentedString(volumeSize)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

