/*
 * LXD
 * The services listed below are referred as .....
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@relxd.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.relxd.lxd.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import org.relxd.lxd.client.model.Cpu;
import org.relxd.lxd.client.model.Disk;
import org.relxd.lxd.client.model.Memory;
import org.relxd.lxd.client.model.Network;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * GetInstancesByNameStateMetadataResponse
 */
@JsonPropertyOrder({
  GetInstancesByNameStateMetadataResponse.JSON_PROPERTY_STATUS,
  GetInstancesByNameStateMetadataResponse.JSON_PROPERTY_STATUS_CODE,
  GetInstancesByNameStateMetadataResponse.JSON_PROPERTY_CPU,
  GetInstancesByNameStateMetadataResponse.JSON_PROPERTY_DISK,
  GetInstancesByNameStateMetadataResponse.JSON_PROPERTY_MEMORY,
  GetInstancesByNameStateMetadataResponse.JSON_PROPERTY_NETWORK,
  GetInstancesByNameStateMetadataResponse.JSON_PROPERTY_PID,
  GetInstancesByNameStateMetadataResponse.JSON_PROPERTY_PROCESSES
})
@javax.annotation.processing.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class GetInstancesByNameStateMetadataResponse {
  public static final String JSON_PROPERTY_STATUS = "status";
  private String status;

  public static final String JSON_PROPERTY_STATUS_CODE = "status_code";
  private BigDecimal statusCode;

  public static final String JSON_PROPERTY_CPU = "cpu";
  private Cpu cpu;

  public static final String JSON_PROPERTY_DISK = "disk";
  private Disk disk;

  public static final String JSON_PROPERTY_MEMORY = "memory";
  private Memory memory;

  public static final String JSON_PROPERTY_NETWORK = "network";
  private Network network;

  public static final String JSON_PROPERTY_PID = "pid";
  private BigDecimal pid;

  public static final String JSON_PROPERTY_PROCESSES = "processes";
  private BigDecimal processes;


  public GetInstancesByNameStateMetadataResponse status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Running", value = "")
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getStatus() {
    return status;
  }


  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatus(String status) {
    this.status = status;
  }


  public GetInstancesByNameStateMetadataResponse statusCode(BigDecimal statusCode) {
    this.statusCode = statusCode;
    return this;
  }

   /**
   * Get statusCode
   * @return statusCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "200", value = "")
  @JsonProperty(JSON_PROPERTY_STATUS_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getStatusCode() {
    return statusCode;
  }


  @JsonProperty(JSON_PROPERTY_STATUS_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatusCode(BigDecimal statusCode) {
    this.statusCode = statusCode;
  }


  public GetInstancesByNameStateMetadataResponse cpu(Cpu cpu) {
    this.cpu = cpu;
    return this;
  }

   /**
   * Get cpu
   * @return cpu
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CPU)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Cpu getCpu() {
    return cpu;
  }


  @JsonProperty(JSON_PROPERTY_CPU)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCpu(Cpu cpu) {
    this.cpu = cpu;
  }


  public GetInstancesByNameStateMetadataResponse disk(Disk disk) {
    this.disk = disk;
    return this;
  }

   /**
   * Get disk
   * @return disk
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DISK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Disk getDisk() {
    return disk;
  }


  @JsonProperty(JSON_PROPERTY_DISK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDisk(Disk disk) {
    this.disk = disk;
  }


  public GetInstancesByNameStateMetadataResponse memory(Memory memory) {
    this.memory = memory;
    return this;
  }

   /**
   * Get memory
   * @return memory
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_MEMORY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Memory getMemory() {
    return memory;
  }


  @JsonProperty(JSON_PROPERTY_MEMORY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMemory(Memory memory) {
    this.memory = memory;
  }


  public GetInstancesByNameStateMetadataResponse network(Network network) {
    this.network = network;
    return this;
  }

   /**
   * Get network
   * @return network
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_NETWORK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Network getNetwork() {
    return network;
  }


  @JsonProperty(JSON_PROPERTY_NETWORK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNetwork(Network network) {
    this.network = network;
  }


  public GetInstancesByNameStateMetadataResponse pid(BigDecimal pid) {
    this.pid = pid;
    return this;
  }

   /**
   * Get pid
   * @return pid
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "13663", value = "")
  @JsonProperty(JSON_PROPERTY_PID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getPid() {
    return pid;
  }


  @JsonProperty(JSON_PROPERTY_PID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPid(BigDecimal pid) {
    this.pid = pid;
  }


  public GetInstancesByNameStateMetadataResponse processes(BigDecimal processes) {
    this.processes = processes;
    return this;
  }

   /**
   * Get processes
   * @return processes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "32", value = "")
  @JsonProperty(JSON_PROPERTY_PROCESSES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getProcesses() {
    return processes;
  }


  @JsonProperty(JSON_PROPERTY_PROCESSES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProcesses(BigDecimal processes) {
    this.processes = processes;
  }


  /**
   * Return true if this GetInstancesByNameStateMetadataResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetInstancesByNameStateMetadataResponse getInstancesByNameStateMetadataResponse = (GetInstancesByNameStateMetadataResponse) o;
    return Objects.equals(this.status, getInstancesByNameStateMetadataResponse.status) &&
        Objects.equals(this.statusCode, getInstancesByNameStateMetadataResponse.statusCode) &&
        Objects.equals(this.cpu, getInstancesByNameStateMetadataResponse.cpu) &&
        Objects.equals(this.disk, getInstancesByNameStateMetadataResponse.disk) &&
        Objects.equals(this.memory, getInstancesByNameStateMetadataResponse.memory) &&
        Objects.equals(this.network, getInstancesByNameStateMetadataResponse.network) &&
        Objects.equals(this.pid, getInstancesByNameStateMetadataResponse.pid) &&
        Objects.equals(this.processes, getInstancesByNameStateMetadataResponse.processes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(status, statusCode, cpu, disk, memory, network, pid, processes);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetInstancesByNameStateMetadataResponse {\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    statusCode: ").append(toIndentedString(statusCode)).append("\n");
    sb.append("    cpu: ").append(toIndentedString(cpu)).append("\n");
    sb.append("    disk: ").append(toIndentedString(disk)).append("\n");
    sb.append("    memory: ").append(toIndentedString(memory)).append("\n");
    sb.append("    network: ").append(toIndentedString(network)).append("\n");
    sb.append("    pid: ").append(toIndentedString(pid)).append("\n");
    sb.append("    processes: ").append(toIndentedString(processes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

