/*
 * LXD
 * The services listed below are referred as .....
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@relxd.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.relxd.lxd.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import org.relxd.lxd.client.model.Properties2;
import org.relxd.lxd.client.model.Templates;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * GetInstancesByNameMetadataResponse
 */
@JsonPropertyOrder({
  GetInstancesByNameMetadataResponse.JSON_PROPERTY_ARCHITECTURE,
  GetInstancesByNameMetadataResponse.JSON_PROPERTY_CREATION_DATE,
  GetInstancesByNameMetadataResponse.JSON_PROPERTY_EXPIRY_DATE,
  GetInstancesByNameMetadataResponse.JSON_PROPERTY_PROPERTIES,
  GetInstancesByNameMetadataResponse.JSON_PROPERTY_TEMPLATES
})
@javax.annotation.processing.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class GetInstancesByNameMetadataResponse {
  public static final String JSON_PROPERTY_ARCHITECTURE = "architecture";
  private String architecture;

  public static final String JSON_PROPERTY_CREATION_DATE = "creation_date";
  private BigDecimal creationDate;

  public static final String JSON_PROPERTY_EXPIRY_DATE = "expiry_date";
  private BigDecimal expiryDate;

  public static final String JSON_PROPERTY_PROPERTIES = "properties";
  private Properties2 properties;

  public static final String JSON_PROPERTY_TEMPLATES = "templates";
  private Templates templates;


  public GetInstancesByNameMetadataResponse architecture(String architecture) {
    this.architecture = architecture;
    return this;
  }

   /**
   * Get architecture
   * @return architecture
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "x86_64", value = "")
  @JsonProperty(JSON_PROPERTY_ARCHITECTURE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getArchitecture() {
    return architecture;
  }


  @JsonProperty(JSON_PROPERTY_ARCHITECTURE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setArchitecture(String architecture) {
    this.architecture = architecture;
  }


  public GetInstancesByNameMetadataResponse creationDate(BigDecimal creationDate) {
    this.creationDate = creationDate;
    return this;
  }

   /**
   * Get creationDate
   * @return creationDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1477146654", value = "")
  @JsonProperty(JSON_PROPERTY_CREATION_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getCreationDate() {
    return creationDate;
  }


  @JsonProperty(JSON_PROPERTY_CREATION_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreationDate(BigDecimal creationDate) {
    this.creationDate = creationDate;
  }


  public GetInstancesByNameMetadataResponse expiryDate(BigDecimal expiryDate) {
    this.expiryDate = expiryDate;
    return this;
  }

   /**
   * Get expiryDate
   * @return expiryDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "0", value = "")
  @JsonProperty(JSON_PROPERTY_EXPIRY_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getExpiryDate() {
    return expiryDate;
  }


  @JsonProperty(JSON_PROPERTY_EXPIRY_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExpiryDate(BigDecimal expiryDate) {
    this.expiryDate = expiryDate;
  }


  public GetInstancesByNameMetadataResponse properties(Properties2 properties) {
    this.properties = properties;
    return this;
  }

   /**
   * Get properties
   * @return properties
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PROPERTIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Properties2 getProperties() {
    return properties;
  }


  @JsonProperty(JSON_PROPERTY_PROPERTIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProperties(Properties2 properties) {
    this.properties = properties;
  }


  public GetInstancesByNameMetadataResponse templates(Templates templates) {
    this.templates = templates;
    return this;
  }

   /**
   * Get templates
   * @return templates
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TEMPLATES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Templates getTemplates() {
    return templates;
  }


  @JsonProperty(JSON_PROPERTY_TEMPLATES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTemplates(Templates templates) {
    this.templates = templates;
  }


  /**
   * Return true if this GetInstancesByNameMetadataResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetInstancesByNameMetadataResponse getInstancesByNameMetadataResponse = (GetInstancesByNameMetadataResponse) o;
    return Objects.equals(this.architecture, getInstancesByNameMetadataResponse.architecture) &&
        Objects.equals(this.creationDate, getInstancesByNameMetadataResponse.creationDate) &&
        Objects.equals(this.expiryDate, getInstancesByNameMetadataResponse.expiryDate) &&
        Objects.equals(this.properties, getInstancesByNameMetadataResponse.properties) &&
        Objects.equals(this.templates, getInstancesByNameMetadataResponse.templates);
  }

  @Override
  public int hashCode() {
    return Objects.hash(architecture, creationDate, expiryDate, properties, templates);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetInstancesByNameMetadataResponse {\n");
    sb.append("    architecture: ").append(toIndentedString(architecture)).append("\n");
    sb.append("    creationDate: ").append(toIndentedString(creationDate)).append("\n");
    sb.append("    expiryDate: ").append(toIndentedString(expiryDate)).append("\n");
    sb.append("    properties: ").append(toIndentedString(properties)).append("\n");
    sb.append("    templates: ").append(toIndentedString(templates)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

