/*
 * LXD
 * The services listed below are referred as .....
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@relxd.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.relxd.lxd.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * GetOperationsResponse
 */
@JsonPropertyOrder({
  GetOperationsResponse.JSON_PROPERTY_SUCCESS,
  GetOperationsResponse.JSON_PROPERTY_RUNNING
})
@javax.annotation.processing.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class GetOperationsResponse {
  public static final String JSON_PROPERTY_SUCCESS = "success";
  private List<String> success = null;

  public static final String JSON_PROPERTY_RUNNING = "running";
  private List<String> running = null;


  public GetOperationsResponse success(List<String> success) {
    this.success = success;
    return this;
  }

  public GetOperationsResponse addSuccessItem(String successItem) {
    if (this.success == null) {
      this.success = new ArrayList<>();
    }
    this.success.add(successItem);
    return this;
  }

   /**
   * Get success
   * @return success
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "[\"/1.0/operations/c0fc0d0d-a997-462b-842b-f8bd0df82507\"]", value = "")
  @JsonProperty(JSON_PROPERTY_SUCCESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getSuccess() {
    return success;
  }


  @JsonProperty(JSON_PROPERTY_SUCCESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSuccess(List<String> success) {
    this.success = success;
  }


  public GetOperationsResponse running(List<String> running) {
    this.running = running;
    return this;
  }

  public GetOperationsResponse addRunningItem(String runningItem) {
    if (this.running == null) {
      this.running = new ArrayList<>();
    }
    this.running.add(runningItem);
    return this;
  }

   /**
   * Get running
   * @return running
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "[\"/1.0/operations/092a8755-fd90-4ce4-bf91-9f87d03fd5bc\"]", value = "")
  @JsonProperty(JSON_PROPERTY_RUNNING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getRunning() {
    return running;
  }


  @JsonProperty(JSON_PROPERTY_RUNNING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRunning(List<String> running) {
    this.running = running;
  }


  /**
   * Return true if this GetOperationsResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetOperationsResponse getOperationsResponse = (GetOperationsResponse) o;
    return Objects.equals(this.success, getOperationsResponse.success) &&
        Objects.equals(this.running, getOperationsResponse.running);
  }

  @Override
  public int hashCode() {
    return Objects.hash(success, running);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetOperationsResponse {\n");
    sb.append("    success: ").append(toIndentedString(success)).append("\n");
    sb.append("    running: ").append(toIndentedString(running)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

