/*
 * LXD
 * The services listed below are referred as .....
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@relxd.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.relxd.lxd.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * ServerConfig
 */
@JsonPropertyOrder({
  ServerConfig.JSON_PROPERTY_CORE_TRUST_PASSWORD,
  ServerConfig.JSON_PROPERTY_CORE_HTTPS_ADDRESS
})
@javax.annotation.processing.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class ServerConfig {
  public static final String JSON_PROPERTY_CORE_TRUST_PASSWORD = "core.trust_password";
  private String coreTrustPassword;

  public static final String JSON_PROPERTY_CORE_HTTPS_ADDRESS = "core.https_address";
  private String coreHttpsAddress;


  public ServerConfig coreTrustPassword(String coreTrustPassword) {
    this.coreTrustPassword = coreTrustPassword;
    return this;
  }

   /**
   * Get coreTrustPassword
   * @return coreTrustPassword
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "my-password", value = "")
  @JsonProperty(JSON_PROPERTY_CORE_TRUST_PASSWORD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCoreTrustPassword() {
    return coreTrustPassword;
  }


  @JsonProperty(JSON_PROPERTY_CORE_TRUST_PASSWORD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCoreTrustPassword(String coreTrustPassword) {
    this.coreTrustPassword = coreTrustPassword;
  }


  public ServerConfig coreHttpsAddress(String coreHttpsAddress) {
    this.coreHttpsAddress = coreHttpsAddress;
    return this;
  }

   /**
   * Get coreHttpsAddress
   * @return coreHttpsAddress
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "[::]:8443", value = "")
  @JsonProperty(JSON_PROPERTY_CORE_HTTPS_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCoreHttpsAddress() {
    return coreHttpsAddress;
  }


  @JsonProperty(JSON_PROPERTY_CORE_HTTPS_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCoreHttpsAddress(String coreHttpsAddress) {
    this.coreHttpsAddress = coreHttpsAddress;
  }


  /**
   * Return true if this ServerConfig object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServerConfig serverConfig = (ServerConfig) o;
    return Objects.equals(this.coreTrustPassword, serverConfig.coreTrustPassword) &&
        Objects.equals(this.coreHttpsAddress, serverConfig.coreHttpsAddress);
  }

  @Override
  public int hashCode() {
    return Objects.hash(coreTrustPassword, coreHttpsAddress);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServerConfig {\n");
    sb.append("    coreTrustPassword: ").append(toIndentedString(coreTrustPassword)).append("\n");
    sb.append("    coreHttpsAddress: ").append(toIndentedString(coreHttpsAddress)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

