/*
 * LXD
 * The services listed below are referred as .....
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@relxd.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.relxd.lxd.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.relxd.lxd.client.model.FileSystemMountOptionsAndThinPoolConfig;
import org.relxd.lxd.client.model.UpdateStoragePoolsByNameVolumesByTypeNameRequest2;
import org.relxd.lxd.client.model.UpdateStoragePoolsByNameVolumesByTypeNameRequestOneOf;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import com.fasterxml.jackson.core.type.TypeReference;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;

import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.JsonToken;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonMappingException;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.MapperFeature;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import com.fasterxml.jackson.databind.ser.std.StdSerializer;
import org.relxd.lxd.client.JSON;

@javax.annotation.processing.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
@JsonDeserialize(using = UpdateStoragePoolsByNameVolumesByTypeNameRequest.UpdateStoragePoolsByNameVolumesByTypeNameRequestDeserializer.class)
@JsonSerialize(using = UpdateStoragePoolsByNameVolumesByTypeNameRequest.UpdateStoragePoolsByNameVolumesByTypeNameRequestSerializer.class)
public class UpdateStoragePoolsByNameVolumesByTypeNameRequest extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(UpdateStoragePoolsByNameVolumesByTypeNameRequest.class.getName());

    public static class UpdateStoragePoolsByNameVolumesByTypeNameRequestSerializer extends StdSerializer<UpdateStoragePoolsByNameVolumesByTypeNameRequest> {
        public UpdateStoragePoolsByNameVolumesByTypeNameRequestSerializer(Class<UpdateStoragePoolsByNameVolumesByTypeNameRequest> t) {
            super(t);
        }

        public UpdateStoragePoolsByNameVolumesByTypeNameRequestSerializer() {
            this(null);
        }

        @Override
        public void serialize(UpdateStoragePoolsByNameVolumesByTypeNameRequest value, JsonGenerator jgen, SerializerProvider provider) throws IOException, JsonProcessingException {
            jgen.writeObject(value.getActualInstance());
        }
    }

    public static class UpdateStoragePoolsByNameVolumesByTypeNameRequestDeserializer extends StdDeserializer<UpdateStoragePoolsByNameVolumesByTypeNameRequest> {
        public UpdateStoragePoolsByNameVolumesByTypeNameRequestDeserializer() {
            this(UpdateStoragePoolsByNameVolumesByTypeNameRequest.class);
        }

        public UpdateStoragePoolsByNameVolumesByTypeNameRequestDeserializer(Class<?> vc) {
            super(vc);
        }

        @Override
        public UpdateStoragePoolsByNameVolumesByTypeNameRequest deserialize(JsonParser jp, DeserializationContext ctxt) throws IOException, JsonProcessingException {
            JsonNode tree = jp.readValueAsTree();
            Object deserialized = null;
            boolean typeCoercion = ctxt.isEnabled(MapperFeature.ALLOW_COERCION_OF_SCALARS);
            int match = 0;
            JsonToken token = tree.traverse(jp.getCodec()).nextToken();
            // deserialize UpdateStoragePoolsByNameVolumesByTypeNameRequest2
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (UpdateStoragePoolsByNameVolumesByTypeNameRequest2.class.equals(Integer.class) || UpdateStoragePoolsByNameVolumesByTypeNameRequest2.class.equals(Long.class) || UpdateStoragePoolsByNameVolumesByTypeNameRequest2.class.equals(Float.class) || UpdateStoragePoolsByNameVolumesByTypeNameRequest2.class.equals(Double.class) || UpdateStoragePoolsByNameVolumesByTypeNameRequest2.class.equals(Boolean.class) || UpdateStoragePoolsByNameVolumesByTypeNameRequest2.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((UpdateStoragePoolsByNameVolumesByTypeNameRequest2.class.equals(Integer.class) || UpdateStoragePoolsByNameVolumesByTypeNameRequest2.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((UpdateStoragePoolsByNameVolumesByTypeNameRequest2.class.equals(Float.class) || UpdateStoragePoolsByNameVolumesByTypeNameRequest2.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (UpdateStoragePoolsByNameVolumesByTypeNameRequest2.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (UpdateStoragePoolsByNameVolumesByTypeNameRequest2.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(UpdateStoragePoolsByNameVolumesByTypeNameRequest2.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'UpdateStoragePoolsByNameVolumesByTypeNameRequest2'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'UpdateStoragePoolsByNameVolumesByTypeNameRequest2'", e);
            }

            // deserialize UpdateStoragePoolsByNameVolumesByTypeNameRequestOneOf
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (UpdateStoragePoolsByNameVolumesByTypeNameRequestOneOf.class.equals(Integer.class) || UpdateStoragePoolsByNameVolumesByTypeNameRequestOneOf.class.equals(Long.class) || UpdateStoragePoolsByNameVolumesByTypeNameRequestOneOf.class.equals(Float.class) || UpdateStoragePoolsByNameVolumesByTypeNameRequestOneOf.class.equals(Double.class) || UpdateStoragePoolsByNameVolumesByTypeNameRequestOneOf.class.equals(Boolean.class) || UpdateStoragePoolsByNameVolumesByTypeNameRequestOneOf.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((UpdateStoragePoolsByNameVolumesByTypeNameRequestOneOf.class.equals(Integer.class) || UpdateStoragePoolsByNameVolumesByTypeNameRequestOneOf.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((UpdateStoragePoolsByNameVolumesByTypeNameRequestOneOf.class.equals(Float.class) || UpdateStoragePoolsByNameVolumesByTypeNameRequestOneOf.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (UpdateStoragePoolsByNameVolumesByTypeNameRequestOneOf.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (UpdateStoragePoolsByNameVolumesByTypeNameRequestOneOf.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(UpdateStoragePoolsByNameVolumesByTypeNameRequestOneOf.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'UpdateStoragePoolsByNameVolumesByTypeNameRequestOneOf'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'UpdateStoragePoolsByNameVolumesByTypeNameRequestOneOf'", e);
            }

            if (match == 1) {
                UpdateStoragePoolsByNameVolumesByTypeNameRequest ret = new UpdateStoragePoolsByNameVolumesByTypeNameRequest();
                ret.setActualInstance(deserialized);
                return ret;
            }
            throw new IOException(String.format("Failed deserialization for UpdateStoragePoolsByNameVolumesByTypeNameRequest: %d classes match result, expected 1", match));
        }

        /**
         * Handle deserialization of the 'null' value.
         */
        @Override
        public UpdateStoragePoolsByNameVolumesByTypeNameRequest getNullValue(DeserializationContext ctxt) throws JsonMappingException {
            throw new JsonMappingException(ctxt.getParser(), "UpdateStoragePoolsByNameVolumesByTypeNameRequest cannot be null");
        }
    }

    // store a list of schema names defined in oneOf
    public static final Map<String, Class<?>> schemas = new HashMap<>();

    public UpdateStoragePoolsByNameVolumesByTypeNameRequest() {
        super("oneOf", Boolean.FALSE);
    }

    public UpdateStoragePoolsByNameVolumesByTypeNameRequest(UpdateStoragePoolsByNameVolumesByTypeNameRequest2 o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public UpdateStoragePoolsByNameVolumesByTypeNameRequest(UpdateStoragePoolsByNameVolumesByTypeNameRequestOneOf o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    static {
        schemas.put("UpdateStoragePoolsByNameVolumesByTypeNameRequest2", UpdateStoragePoolsByNameVolumesByTypeNameRequest2.class);
        schemas.put("UpdateStoragePoolsByNameVolumesByTypeNameRequestOneOf", UpdateStoragePoolsByNameVolumesByTypeNameRequestOneOf.class);
        JSON.registerDescendants(UpdateStoragePoolsByNameVolumesByTypeNameRequest.class, Collections.unmodifiableMap(schemas));
    }

    @Override
    public Map<String, Class<?>> getSchemas() {
        return UpdateStoragePoolsByNameVolumesByTypeNameRequest.schemas;
    }

    /**
     * Set the instance that matches the oneOf child schema, check
     * the instance parameter is valid against the oneOf child schemas:
     * UpdateStoragePoolsByNameVolumesByTypeNameRequest2, UpdateStoragePoolsByNameVolumesByTypeNameRequestOneOf
     *
     * It could be an instance of the 'oneOf' schemas.
     * The oneOf child schemas may themselves be a composed schema (allOf, anyOf, oneOf).
     */
    @Override
    public void setActualInstance(Object instance) {
        if (JSON.isInstanceOf(UpdateStoragePoolsByNameVolumesByTypeNameRequest2.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(UpdateStoragePoolsByNameVolumesByTypeNameRequestOneOf.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        throw new RuntimeException("Invalid instance type. Must be UpdateStoragePoolsByNameVolumesByTypeNameRequest2, UpdateStoragePoolsByNameVolumesByTypeNameRequestOneOf");
    }

    /**
     * Get the actual instance, which can be the following:
     * UpdateStoragePoolsByNameVolumesByTypeNameRequest2, UpdateStoragePoolsByNameVolumesByTypeNameRequestOneOf
     *
     * @return The actual instance (UpdateStoragePoolsByNameVolumesByTypeNameRequest2, UpdateStoragePoolsByNameVolumesByTypeNameRequestOneOf)
     */
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `UpdateStoragePoolsByNameVolumesByTypeNameRequest2`. If the actual instance is not `UpdateStoragePoolsByNameVolumesByTypeNameRequest2`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `UpdateStoragePoolsByNameVolumesByTypeNameRequest2`
     * @throws ClassCastException if the instance is not `UpdateStoragePoolsByNameVolumesByTypeNameRequest2`
     */
    public UpdateStoragePoolsByNameVolumesByTypeNameRequest2 getUpdateStoragePoolsByNameVolumesByTypeNameRequest2() throws ClassCastException {
        return (UpdateStoragePoolsByNameVolumesByTypeNameRequest2)super.getActualInstance();
    }

    /**
     * Get the actual instance of `UpdateStoragePoolsByNameVolumesByTypeNameRequestOneOf`. If the actual instance is not `UpdateStoragePoolsByNameVolumesByTypeNameRequestOneOf`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `UpdateStoragePoolsByNameVolumesByTypeNameRequestOneOf`
     * @throws ClassCastException if the instance is not `UpdateStoragePoolsByNameVolumesByTypeNameRequestOneOf`
     */
    public UpdateStoragePoolsByNameVolumesByTypeNameRequestOneOf getUpdateStoragePoolsByNameVolumesByTypeNameRequestOneOf() throws ClassCastException {
        return (UpdateStoragePoolsByNameVolumesByTypeNameRequestOneOf)super.getActualInstance();
    }

}

