/*
 * LXD
 * The services listed below are referred as .....
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@competitionlabs.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.relxd.lxd.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.relxd.lxd.model.Fds1;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for CreateInstancesByNameExecResponse1
 */
public class CreateInstancesByNameExecResponse1Test {
    private final CreateInstancesByNameExecResponse1 model = new CreateInstancesByNameExecResponse1();

    /**
     * Model tests for CreateInstancesByNameExecResponse1
     */
    @Test
    public void testCreateInstancesByNameExecResponse1() {
        // TODO: test CreateInstancesByNameExecResponse1
    }

    /**
     * Test the property 'fds'
     */
    @Test
    public void fdsTest() {
        // TODO: test fds
    }

}
