/*
 * LXD
 * The services listed below are referred as .....
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@competitionlabs.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.relxd.lxd.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for GetInstancesByNameBackupsByNameResponse
 */
public class GetInstancesByNameBackupsByNameResponseTest {
    private final GetInstancesByNameBackupsByNameResponse model = new GetInstancesByNameBackupsByNameResponse();

    /**
     * Model tests for GetInstancesByNameBackupsByNameResponse
     */
    @Test
    public void testGetInstancesByNameBackupsByNameResponse() {
        // TODO: test GetInstancesByNameBackupsByNameResponse
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'creationDate'
     */
    @Test
    public void creationDateTest() {
        // TODO: test creationDate
    }

    /**
     * Test the property 'expiryDate'
     */
    @Test
    public void expiryDateTest() {
        // TODO: test expiryDate
    }

    /**
     * Test the property 'instanceOnly'
     */
    @Test
    public void instanceOnlyTest() {
        // TODO: test instanceOnly
    }

    /**
     * Test the property 'optimizedStorage'
     */
    @Test
    public void optimizedStorageTest() {
        // TODO: test optimizedStorage
    }

}
