/*
 * LXD
 * The services listed below are referred as .....
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@relxd.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.relxd.lxd.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.relxd.lxd.model.Properties4;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for UpdateImagesFingerprintRequest
 */
public class UpdateImagesFingerprintRequestTest {
    private final UpdateImagesFingerprintRequest model = new UpdateImagesFingerprintRequest();

    /**
     * Model tests for UpdateImagesFingerprintRequest
     */
    @Test
    public void testUpdateImagesFingerprintRequest() {
        // TODO: test UpdateImagesFingerprintRequest
    }

    /**
     * Test the property 'autoUpdate'
     */
    @Test
    public void autoUpdateTest() {
        // TODO: test autoUpdate
    }

    /**
     * Test the property 'properties'
     */
    @Test
    public void propertiesTest() {
        // TODO: test properties
    }

    /**
     * Test the property '_public'
     */
    @Test
    public void _publicTest() {
        // TODO: test _public
    }

}
