/*
 * LXD
 * The services listed below are referred as .....
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@relxd.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.relxd.lxd.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Fds2
 */
public class Fds2Test {
    private final Fds2 model = new Fds2();

    /**
     * Model tests for Fds2
     */
    @Test
    public void testFds2() {
        // TODO: test Fds2
    }

    /**
     * Test the property '_0'
     */
    @Test
    public void _0Test() {
        // TODO: test _0
    }

    /**
     * Test the property 'control'
     */
    @Test
    public void controlTest() {
        // TODO: test control
    }

}
