/*
 * LXD
 * The services listed below are referred as .....
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@relxd.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.relxd.lxd.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for NetworkIPConfig
 */
public class NetworkIPConfigTest {
    private final NetworkIPConfig model = new NetworkIPConfig();

    /**
     * Model tests for NetworkIPConfig
     */
    @Test
    public void testNetworkIPConfig() {
        // TODO: test NetworkIPConfig
    }

    /**
     * Test the property 'ipv4Address'
     */
    @Test
    public void ipv4AddressTest() {
        // TODO: test ipv4Address
    }

    /**
     * Test the property 'ipv6Address'
     */
    @Test
    public void ipv6AddressTest() {
        // TODO: test ipv6Address
    }

    /**
     * Test the property 'ipv6Nat'
     */
    @Test
    public void ipv6NatTest() {
        // TODO: test ipv6Nat
    }

}
