/*
 * LXD
 * The services listed below are referred as .....
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@relxd.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.relxd.lxd.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.relxd.lxd.client.model.FileSystemMountOptionsAndThinPoolConfig;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for UpdateStoragePoolsByNameVolumesByTypeNameRequest2
 */
public class UpdateStoragePoolsByNameVolumesByTypeNameRequest2Test {
    private final UpdateStoragePoolsByNameVolumesByTypeNameRequest2 model = new UpdateStoragePoolsByNameVolumesByTypeNameRequest2();

    /**
     * Model tests for UpdateStoragePoolsByNameVolumesByTypeNameRequest2
     */
    @Test
    public void testUpdateStoragePoolsByNameVolumesByTypeNameRequest2() {
        // TODO: test UpdateStoragePoolsByNameVolumesByTypeNameRequest2
    }

    /**
     * Test the property 'config'
     */
    @Test
    public void configTest() {
        // TODO: test config
    }

}
