/*
 * LXD
 * The services listed below are referred as .....
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@relxd.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.relxd.lxd.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import org.relxd.lxd.client.model.GetStoragePoolsByNameVolumesByTypeNameResponseAllOf;
import org.relxd.lxd.client.model.GetStoragePoolsByNameVolumesByTypeNameResponseMetadata;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for GetStoragePoolsByNameVolumesByTypeNameResponseAllOf
 */
public class GetStoragePoolsByNameVolumesByTypeNameResponseAllOfTest {
    private final GetStoragePoolsByNameVolumesByTypeNameResponseAllOf model = new GetStoragePoolsByNameVolumesByTypeNameResponseAllOf();

    /**
     * Model tests for GetStoragePoolsByNameVolumesByTypeNameResponseAllOf
     */
    @Test
    public void testGetStoragePoolsByNameVolumesByTypeNameResponseAllOf() {
        // TODO: test GetStoragePoolsByNameVolumesByTypeNameResponseAllOf
    }

    /**
     * Test the property 'metadata'
     */
    @Test
    public void metadataTest() {
        // TODO: test metadata
    }

    /**
     * Test the property 'errorCode'
     */
    @Test
    public void errorCodeTest() {
        // TODO: test errorCode
    }

    /**
     * Test the property 'error'
     */
    @Test
    public void errorTest() {
        // TODO: test error
    }

}
