/*
 * LXD
 * The services listed below are referred as .....
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@relxd.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.relxd.lxd.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Secrets
 */
public class SecretsTest {
    private final Secrets model = new Secrets();

    /**
     * Model tests for Secrets
     */
    @Test
    public void testSecrets() {
        // TODO: test Secrets
    }

    /**
     * Test the property 'control'
     */
    @Test
    public void controlTest() {
        // TODO: test control
    }

    /**
     * Test the property 'criu'
     */
    @Test
    public void criuTest() {
        // TODO: test criu
    }

    /**
     * Test the property 'fs'
     */
    @Test
    public void fsTest() {
        // TODO: test fs
    }

}
