/*
 * LXD
 * The services listed below are referred as .....
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@relxd.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.relxd.lxd.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * This is a map of config parameters to be used during instance creation. The keys for this map are the keys from instance.md file (https://github.com/lxc/lxd/blob/master/doc/instances.md#keyvalue-configuration) and values are the fields to set.
 */
@ApiModel(description = "This is a map of config parameters to be used during instance creation. The keys for this map are the keys from instance.md file (https://github.com/lxc/lxd/blob/master/doc/instances.md#keyvalue-configuration) and values are the fields to set.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-11-23T15:31:41.267118Z[Europe/London]")
public class CreateInstancesRequestConfig {
  public static final String SERIALIZED_NAME_CREATE_INSTANCES_REQUEST_CONFIG = "createInstancesRequestConfig";
  @SerializedName(SERIALIZED_NAME_CREATE_INSTANCES_REQUEST_CONFIG)
  private Map<String, Object> createInstancesRequestConfig = null;


  public CreateInstancesRequestConfig createInstancesRequestConfig(Map<String, Object> createInstancesRequestConfig) {

    this.createInstancesRequestConfig = createInstancesRequestConfig;
    return this;
  }

  public CreateInstancesRequestConfig putCreateInstancesRequestConfigItem(String key, Object createInstancesRequestConfigItem) {
    if (this.createInstancesRequestConfig == null) {
      this.createInstancesRequestConfig = new HashMap<String, Object>();
    }
    this.createInstancesRequestConfig.put(key, createInstancesRequestConfigItem);
    return this;
  }

  /**
   * This is a map of config parameters to be used during instance creation. The keys for this map are the keys from instance.md file (https://github.com/lxc/lxd/blob/master/doc/instances.md#keyvalue-configuration) and values are the fields to set.
   * @return createInstancesRequestConfig
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "{\"limits.cpu\":\"2\",\"limits.memory\":\"512MB\"}", value = "This is a map of config parameters to be used during instance creation. The keys for this map are the keys from instance.md file (https://github.com/lxc/lxd/blob/master/doc/instances.md#keyvalue-configuration) and values are the fields to set.")

  public Map<String, Object> getCreateInstancesRequestConfig() {
    return createInstancesRequestConfig;
  }


  public void setCreateInstancesRequestConfig(Map<String, Object> createInstancesRequestConfig) {
    this.createInstancesRequestConfig = createInstancesRequestConfig;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateInstancesRequestConfig createInstancesRequestConfig = (CreateInstancesRequestConfig) o;
    return Objects.equals(this.createInstancesRequestConfig, createInstancesRequestConfig.createInstancesRequestConfig);
  }

  @Override
  public int hashCode() {
    return Objects.hash(createInstancesRequestConfig);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateInstancesRequestConfig {\n");
    sb.append("    createInstancesRequestConfig: ").append(toIndentedString(createInstancesRequestConfig)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

